### ISSUE TITLE
What do you use to stream NTRIP corrections into the Novatel receiver?

### ISSUE THREAD

**Issue by jlblancoc** [swri-robotics/novatel_gps_driver#126]
Hi there:

I'm considering moving from a former custom C++ driver to this package, but I miss the part of feeding NTRIP correction messages from an external source to the receiver. Is this handled in some way by this or related package? Or should we keep using [that part from our former solution](https://docs.mrpt.org/reference/latest/class_mrpt_hwdrivers_CNTRIPEmitter.html)? 

Thanks for the great package 🙏

**Comment by danthony06** [comment]
Sorry for the delayed response, but this should be implemented now via a couple of fixed issues (primarily https://github.com/swri-robotics/novatel_gps_driver/pull/160). The driver can now write RTCM corrections straight to the receiver, so you do not need a separate emitter writing to the port. You point it at a port with `correction_device` and publish corrections on `/rtcm` as `rtcm_msgs/Message`:

Your configuration should look something like this:

```yaml
novatel_gps_node:
  ros__parameters:
    device: /dev/ttyUSB0
    correction_device: /dev/ttyUSB1
    correction_connection_type: serial
    correction_serial_baud: 115200
    publish_nmea_sentences: true
```

There's a few things to note:

- The correction port needs INTERFACEMODE <port> RTCMV3 on the receiver, which stops that port accepting NovAtel commands, so it is normally a different port than the one the driver reads logs from. If your receiver has only one usable port, set correction_device to the same string as device and configure that port with INTERFACEMODE <port> AUTO, which accepts both commands and corrections.
- The driver is not an NTRIP client. It has no caster login, mountpoint or reconnect logic, so pair it with ntrip_client or keep using CNTRIPEmitter pointed at the correction port. Check which message type your NTRIP client publishes, since the driver subscribes to rtcm_msgs/Message.
- If your caster expects periodic GGA from the rover, set publish_nmea_sentences: true and feed /nmea_sentence (nmea_msgs/Sentence) to your NTRIP client.
